### ISSUE TITLE
extends Monolog

### ISSUE THREAD

**Issue by naoki-kobayashi-sms** [nekonomokochan/php-json-logger#59]
# Problem
An uneasy to use in Laravel applications.

# Proposal for solution
extends [Monolog](https://github.com/Seldaek/monolog/blob/master/src/Monolog/Logger.php)

**Comment by keitakn** [comment]
@naoki-kobayashi-sms 

Thank you for telling me the problem.

I will restructure `Nekonomokochan\Php Json Logger\ Logger ` as a class that extend `Monolog`.

But this is an incompatible change.

So I will upload major version of package.

**Comment by keitakn** [comment]
@naoki-kobayashi-sms 

I responded to this issue.

https://github.com/nekonomokochan/php-json-logger/pulls

You can install this version from https://packagist.org/packages/nekonomokochan/php-json-logger .

When you receive a reply from me, I will publish a new version of Package.

**Comment by naoki-kobayashi-sms** [comment]
Awsome!
I could use this one very easy in my Laravel application. Thanks!

**Comment by keitakn** [comment]
@naoki-kobayashi-sms 

Thanks for the reply.

I will merge my PR and publish a new version of the package.

Thanks.
